//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskFrame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeskFrame.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update. Check for update on start and every 6 hours.
        /// </summary>
        public static string DeskFrameFrameSettings_AutoUpdate {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default frame style.
        /// </summary>
        public static string DeskFrameFrameSettings_DefaultFrameStyle {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DefaultFrameStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click on desktop to toggle hide every frame.
        /// </summary>
        public static string DeskFrameFrameSettings_DoubleClickHide {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DoubleClickHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string DeskFrameFrameSettings_ExportSettings {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with .
        /// </summary>
        public static string DeskFrameFrameSettings_MadewithSpace {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.MadewithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset default style.
        /// </summary>
        public static string DeskFrameFrameSettings_ResetDefaultStyle {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ResetDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeskFrame settings.
        /// </summary>
        public static string DeskFrameFrameSettings_TitleBarText {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string FrameGridView_DateModified {
            get {
                return ResourceManager.GetString("FrameGridView.DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FrameGridView_Name {
            get {
                return ResourceManager.GetString("FrameGridView.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FrameGridView_Size {
            get {
                return ResourceManager.GetString("FrameGridView.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation speed:.
        /// </summary>
        public static string FrameSettings_AnimationSpeed {
            get {
                return ResourceManager.GetString("FrameSettings.AnimationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand on cursor over.
        /// </summary>
        public static string FrameSettings_AutoExpandonCursor {
            get {
                return ResourceManager.GetString("FrameSettings.AutoExpandonCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color (hex): .
        /// </summary>
        public static string FrameSettings_BackgroundColor {
            get {
                return ResourceManager.GetString("FrameSettings.BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color (hex):.
        /// </summary>
        public static string FrameSettings_BorderColor {
            get {
                return ResourceManager.GetString("FrameSettings.BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File items.
        /// </summary>
        public static string FrameSettings_CategoryFileItems {
            get {
                return ResourceManager.GetString("FrameSettings.CategoryFileItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string FrameSettings_CategoryMiscellaneous {
            get {
                return ResourceManager.GetString("FrameSettings.CategoryMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar.
        /// </summary>
        public static string FrameSettings_CategoryTitleBar {
            get {
                return ResourceManager.GetString("FrameSettings.CategoryTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change folder.
        /// </summary>
        public static string FrameSettings_ChangeFolder {
            get {
                return ResourceManager.GetString("FrameSettings.ChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change style.
        /// </summary>
        public static string FrameSettings_ChangeStyle {
            get {
                return ResourceManager.GetString("FrameSettings.ChangeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show folder size in menu.
        /// </summary>
        public static string FrameSettings_CheckFolderSize {
            get {
                return ResourceManager.GetString("FrameSettings.CheckFolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string FrameSettings_Font {
            get {
                return ResourceManager.GetString("FrameSettings.Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide files (regex):.
        /// </summary>
        public static string FrameSettings_HideFilesRegex {
            get {
                return ResourceManager.GetString("FrameSettings.HideFilesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon size:.
        /// </summary>
        public static string FrameSettings_IconSize {
            get {
                return ResourceManager.GetString("FrameSettings.IconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle opacity:.
        /// </summary>
        public static string FrameSettings_IdleOpacityLabel {
            get {
                return ResourceManager.GetString("FrameSettings.IdleOpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string FrameSettings_RevertButton {
            get {
                return ResourceManager.GetString("FrameSettings.RevertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string FrameSettings_Searchdot {
            get {
                return ResourceManager.GetString("FrameSettings.Searchdot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions.
        /// </summary>
        public static string FrameSettings_ShowFileExtensionIcon {
            get {
                return ResourceManager.GetString("FrameSettings.ShowFileExtensionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files (regex):.
        /// </summary>
        public static string FrameSettings_ShowFilesRegex {
            get {
                return ResourceManager.GetString("FrameSettings.ShowFilesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden files.
        /// </summary>
        public static string FrameSettings_ShowHiddenFilesIcon {
            get {
                return ResourceManager.GetString("FrameSettings.ShowHiddenFilesIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon text.
        /// </summary>
        public static string FrameSettings_ShowIconText {
            get {
                return ResourceManager.GetString("FrameSettings.ShowIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last accessed items first.
        /// </summary>
        public static string FrameSettings_ShowLastAccessedItem {
            get {
                return ResourceManager.GetString("FrameSettings.ShowLastAccessedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible on virtual desktop:.
        /// </summary>
        public static string FrameSettings_ShowOnVirtualDesktopLabel {
            get {
                return ResourceManager.GetString("FrameSettings.ShowOnVirtualDesktopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All (or e.g. 1,2,3).
        /// </summary>
        public static string FrameSettings_ShowOnVirtualDesktopPlaceHolder {
            get {
                return ResourceManager.GetString("FrameSettings.ShowOnVirtualDesktopPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show shortcut arrow.
        /// </summary>
        public static string FrameSettings_ShowShortcutArrow {
            get {
                return ResourceManager.GetString("FrameSettings.ShowShortcutArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text alignment:.
        /// </summary>
        public static string FrameSettings_TextAlignment {
            get {
                return ResourceManager.GetString("FrameSettings.TextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color (hex):.
        /// </summary>
        public static string FrameSettings_TextColor {
            get {
                return ResourceManager.GetString("FrameSettings.TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text shadow color (hex):.
        /// </summary>
        public static string FrameSettings_TextShadowColor {
            get {
                return ResourceManager.GetString("FrameSettings.TextShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text size:.
        /// </summary>
        public static string FrameSettings_TextSize {
            get {
                return ResourceManager.GetString("FrameSettings.TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar icons:.
        /// </summary>
        public static string FrameSettings_TitleBarIcons {
            get {
                return ResourceManager.GetString("FrameSettings.TitleBarIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar text:.
        /// </summary>
        public static string FrameSettings_TitleBarText {
            get {
                return ResourceManager.GetString("FrameSettings.TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop a folder.
        /// </summary>
        public static string showFolderInGrid_DropFolder {
            get {
                return ResourceManager.GetString("showFolderInGrid.DropFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change view.
        /// </summary>
        public static string TitleBarContextMenu_ChangeView {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.ChangeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details view.
        /// </summary>
        public static string TitleBarContextMenu_DetailsView {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.DetailsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions.
        /// </summary>
        public static string TitleBarContextMenu_FileExtensions {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Settings.
        /// </summary>
        public static string TitleBarContextMenu_FrameSettings {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.FrameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid view.
        /// </summary>
        public static string TitleBarContextMenu_GridView {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden files.
        /// </summary>
        public static string TitleBarContextMenu_HiddenFiles {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.HiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: .
        /// </summary>
        public static string TitleBarContextMenu_Info_Files {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders: .
        /// </summary>
        public static string TitleBarContextMenu_Info_Folders {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Size: .
        /// </summary>
        public static string TitleBarContextMenu_Info_FolderSize {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.FolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hidden).
        /// </summary>
        public static string TitleBarContextMenu_Info_HiddenFiles {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.HiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated: .
        /// </summary>
        public static string TitleBarContextMenu_Info_LastUpdated {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock frame.
        /// </summary>
        public static string TitleBarContextMenu_LockFrame {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.LockFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string TitleBarContextMenu_OpenFolder {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string TitleBarContextMenu_Reload {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string TitleBarContextMenu_Remove {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove it?.
        /// </summary>
        public static string TitleBarContextMenu_RemoveMessageBox_Content {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.RemoveMessageBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TitleBarContextMenu_RemoveMessageBox_No {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.RemoveMessageBox.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string TitleBarContextMenu_RemoveMessageBox_Title {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.RemoveMessageBox.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TitleBarContextMenu_RemoveMessageBox_Yes {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.RemoveMessageBox.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string TitleBarContextMenu_Sortby {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_Ascending {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_DateCreated {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_DateModified {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_Descending {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FileSize {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FileType {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FolderIder_First {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FolderIder.First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FolderIder_Last {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FolderIder.Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FolderIder_None {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FolderIder.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder order.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FolderOrder {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FolderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_Name {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock frame.
        /// </summary>
        public static string TitleBarContextMenu_UnlockFrame {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.UnlockFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add frame.
        /// </summary>
        public static string TrayContextMenu_AddFrame {
            get {
                return ResourceManager.GetString("TrayContextMenu.AddFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string TrayContextMenu_CheckUpdateButton {
            get {
                return ResourceManager.GetString("TrayContextMenu.CheckUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayContextMenu_Exit {
            get {
                return ResourceManager.GetString("TrayContextMenu.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TrayContextMenu_Settings {
            get {
                return ResourceManager.GetString("TrayContextMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on login.
        /// </summary>
        public static string TrayContextMenu_StartOnLogin {
            get {
                return ResourceManager.GetString("TrayContextMenu.StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit github.
        /// </summary>
        public static string TrayContextMenu_VisitGithub {
            get {
                return ResourceManager.GetString("TrayContextMenu.VisitGithub", resourceCulture);
            }
        }
    }
}
